#!/usr/bin/env python3
"""Render supplementary Xenium–VisiumHD D1-Island alignment videos.

For each requested donor, this script creates three final-coordinate videos:

* D1 Island A highlighted;
* D1 Island B highlighted;
* D1 Island A and B highlighted together.

The colors, background layers, opacities, point styles, and physical depths
match the interactive 3D HTML scenes generated by
``06_Xenium_VHD_aligned_plot.py``. All Xenium and VisiumHD observations remain
visible; non-highlighted observations are grey. Displayed z depth is reversed,
as in those HTML files. Each movie starts at the frontal XY plane, rotates once
about the ML axis, and then rotates once about the DV axis.
"""

from __future__ import annotations

import argparse
import os
import subprocess
import time
from dataclasses import dataclass
from pathlib import Path
from typing import Callable, Sequence

os.environ["PYVISTA_OFF_SCREEN"] = "true"
os.environ.setdefault("PYVISTA_EGL", "true")
os.environ.setdefault("VTK_DEFAULT_OPENGL_WINDOW", "vtkEGLRenderWindow")
os.environ.pop("DISPLAY", None)
os.environ.setdefault("MPLCONFIGDIR", "/tmp/matplotlib")

import cv2
import numpy as np
import pandas as pd
import pyvista as pv


DONORS = ("Br6660", "Br6436")
CONTENT_OPTIONS = ("d1-a", "d1-b", "d1-a-b")

BACKGROUND_XENIUM_COLOR = "#8F8F8F"
BACKGROUND_VHD_COLOR = "#585858"
HIGHLIGHT_PALETTE = {
    "D1_Island_A": "#00BFFF",
    "D1_Island_B": "#00FF0D",
}
VHD_HIGHLIGHT_PALETTE = {
    "D1_Island_A": "#0B3C5D",
    "D1_Island_B": "#006400",
}

THREE_D_POINT_SIZE = 3.0
XENIUM_BACKGROUND_OPACITY = 0.05
VHD_BACKGROUND_OPACITY = 0.10
XENIUM_HIGHLIGHT_OPACITY = 0.55
VHD_HIGHLIGHT_OPACITY = 1.00


@dataclass(frozen=True)
class PairSpec:
    donor: str
    xenium_sample: str
    vhd_sample: str
    xenium_depth: float
    vhd_depth: float

    @property
    def tag(self) -> str:
        return f"{self.xenium_sample}-{self.vhd_sample}"


PAIR_SPECS = (
    PairSpec("Br6660", "Br6660_NAc4_2080", "VHD_H1_8MTH2TQ_A1", 2080, 2040),
    PairSpec("Br6660", "Br6660_NAc6_3080", "VHD_H1_M3TCP9V_A1", 3080, 3040),
    PairSpec("Br6660", "Br6660_NAc7_3580", "VHD_H1_XKYDCP3_A1", 3580, 3540),
    PairSpec("Br6660", "Br6660_NAc7_3580", "VHD_H1_8MTH2TQ_D1", 3580, 3630),
    PairSpec("Br6660", "Br6660_Nac10_4080", "VHD_H1_XKYDCP3_D1", 4080, 4120),
    PairSpec("Br6660", "Br6660_NAc8_4580", "VHD_H1_M3TCP9V_D1", 4580, 4550),
    PairSpec("Br6436", "Br6436_Nac1_650", "VHD_H1_XNQ4F2B_A1", 650, 630),
    PairSpec("Br6436", "Br6436_Nac_9_4650", "VHD_H1_XNQ4F2B_D1", 4650, 4630),
)


@dataclass
class DonorCloud:
    donor: str
    xenium_xyz: np.ndarray
    xenium_labels: np.ndarray
    vhd_xyz: np.ndarray
    vhd_labels: np.ndarray


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--donors",
        nargs="+",
        choices=DONORS,
        default=list(DONORS),
        help="Donors to render (default: Br6660 and Br6436).",
    )
    parser.add_argument(
        "--contents",
        nargs="+",
        choices=CONTENT_OPTIONS,
        default=list(CONTENT_OPTIONS),
        help="Highlighted D1-Island content (default: all three videos).",
    )
    parser.add_argument("--fps", type=int, default=30)
    parser.add_argument("--seconds-per-rotation", type=float, default=8.0)
    parser.add_argument(
        "--window-size",
        type=int,
        nargs=2,
        metavar=("WIDTH", "HEIGHT"),
        default=(1440, 1440),
    )
    parser.add_argument("--point-size", type=float, default=THREE_D_POINT_SIZE)
    parser.add_argument("--overwrite", action="store_true")
    args = parser.parse_args()
    if args.fps < 1:
        parser.error("--fps must be positive")
    if not np.isfinite(args.seconds_per_rotation) or args.seconds_per_rotation <= 0:
        parser.error("--seconds-per-rotation must be positive and finite")
    if any(value < 2 or value % 2 for value in args.window_size):
        parser.error("--window-size values must be positive even integers")
    if not np.isfinite(args.point_size) or args.point_size <= 0:
        parser.error("--point-size must be positive and finite")
    if len(args.donors) != len(set(args.donors)):
        parser.error("--donors contains duplicates")
    if len(args.contents) != len(set(args.contents)):
        parser.error("--contents contains duplicates")
    return args


def git_root() -> Path:
    return Path(
        subprocess.check_output(
            ["git", "rev-parse", "--show-toplevel"], text=True
        ).strip()
    )


def xenium_coordinate_path(root: Path, donor: str) -> Path:
    return (
        root
        / "processed-data"
        / "05_Xenium_alignment"
        / f"module02_Spateo_second_pass_{donor}"
        / f"{donor}_second_pass_coordinates.csv"
    )


def vhd_coordinate_path(root: Path, spec: PairSpec) -> Path:
    return (
        root
        / "processed-data"
        / "11_Xenium_VisiumHD_alignment"
        / "module_02_Spateo_second_pass"
        / spec.tag
        / f"{spec.tag}_second_pass_coordinates.csv"
    )


def output_path(root: Path, donor: str, content: str) -> Path:
    label = {
        "d1-a": "D1_Island_A",
        "d1-b": "D1_Island_B",
        "d1-a-b": "D1_Island_A_B",
    }[content]
    return (
        root
        / "plots"
        / "11_Xenium_VisiumHD_alignment"
        / "supp_video"
        / f"{donor}_Xenium_VisiumHD_{label}.mp4"
    )


def prepare_output(path: Path, overwrite: bool) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    if path.exists() and not overwrite:
        raise FileExistsError(f"Output exists; use --overwrite: {path}")
    if path.exists():
        path.unlink()


def check_single_value(
    frame: pd.DataFrame,
    column: str,
    expected: str | float,
    source: Path,
) -> None:
    values = frame[column].dropna().unique()
    if len(values) != 1:
        raise ValueError(f"{source}: expected one value in {column}; got {values}")
    observed = values[0]
    if isinstance(expected, float):
        if not np.isclose(float(observed), expected):
            raise ValueError(f"{source}: {column}={observed}; expected {expected}")
    elif str(observed) != expected:
        raise ValueError(f"{source}: {column}={observed!r}; expected {expected!r}")


def load_xenium_donor(root: Path, donor: str) -> pd.DataFrame:
    path = xenium_coordinate_path(root, donor)
    required = [
        "donor", "sample", "cell_id", "cell_type",
        "x_second_pass", "y_second_pass", "z_height",
    ]
    frame = pd.read_csv(path, usecols=required)
    if set(frame["donor"].dropna().astype(str)) != {donor}:
        raise ValueError(f"Xenium donor mismatch: {path}")
    if frame["cell_id"].isna().any() or frame["cell_id"].astype(str).duplicated().any():
        raise ValueError(f"Xenium cell IDs must be present and unique: {path}")
    if frame[["x_second_pass", "y_second_pass", "z_height"]].isna().any().any():
        raise ValueError(f"Missing Xenium coordinates: {path}")
    if frame["cell_type"].isna().any():
        raise ValueError(f"Missing Xenium cell types: {path}")
    return frame


def load_vhd_pair(root: Path, spec: PairSpec) -> pd.DataFrame:
    path = vhd_coordinate_path(root, spec)
    required = [
        "donor", "xenium_sample", "vhd_sample", "vhd_obs_id",
        "x_second_pass", "y_second_pass", "xenium_z_height",
        "vhd_z_height", "Spatial_Domain",
    ]
    frame = pd.read_csv(path, usecols=required)
    check_single_value(frame, "donor", spec.donor, path)
    check_single_value(frame, "xenium_sample", spec.xenium_sample, path)
    check_single_value(frame, "vhd_sample", spec.vhd_sample, path)
    check_single_value(frame, "xenium_z_height", float(spec.xenium_depth), path)
    check_single_value(frame, "vhd_z_height", float(spec.vhd_depth), path)
    if frame["vhd_obs_id"].isna().any() or frame["vhd_obs_id"].astype(str).duplicated().any():
        raise ValueError(
            f"VisiumHD observation IDs must be present and unique: {path}"
        )
    if frame[["x_second_pass", "y_second_pass", "vhd_z_height"]].isna().any().any():
        raise ValueError(f"Missing VisiumHD coordinates: {path}")
    if frame["Spatial_Domain"].isna().any():
        raise ValueError(f"Missing VisiumHD spatial domains: {path}")
    return frame


def build_donor_cloud(root: Path, donor: str) -> DonorCloud:
    xenium = load_xenium_donor(root, donor).sort_values(
        ["z_height", "sample", "cell_id"], kind="stable"
    )
    specs = [spec for spec in PAIR_SPECS if spec.donor == donor]
    if not specs:
        raise ValueError(f"No Xenium–VisiumHD pairs configured for {donor}")
    vhd = pd.concat(
        [load_vhd_pair(root, spec) for spec in specs], ignore_index=True
    ).sort_values(["vhd_z_height", "vhd_sample", "vhd_obs_id"], kind="stable")

    xenium_xyz = xenium[
        ["x_second_pass", "y_second_pass", "z_height"]
    ].to_numpy(dtype=np.float32)
    vhd_xyz = vhd[
        ["x_second_pass", "y_second_pass", "vhd_z_height"]
    ].to_numpy(dtype=np.float32)
    # Match the displayed physical-z orientation of the existing HTML files.
    xenium_xyz[:, 2] *= -1
    vhd_xyz[:, 2] *= -1
    return DonorCloud(
        donor=donor,
        xenium_xyz=xenium_xyz,
        xenium_labels=xenium["cell_type"].astype(str).to_numpy(),
        vhd_xyz=vhd_xyz,
        vhd_labels=vhd["Spatial_Domain"].astype(str).to_numpy(),
    )


def highlighted_celltypes(content: str) -> tuple[str, ...]:
    return {
        "d1-a": ("D1_Island_A",),
        "d1-b": ("D1_Island_B",),
        "d1-a-b": ("D1_Island_A", "D1_Island_B"),
    }[content]


def add_point_layer(
    plotter: pv.Plotter,
    points: np.ndarray,
    color: str,
    opacity: float,
    point_size: float,
    render_as_spheres: bool,
) -> None:
    if not len(points):
        return
    plotter.add_mesh(
        pv.PolyData(points),
        color=color,
        opacity=opacity,
        style="points",
        point_size=point_size,
        render_points_as_spheres=render_as_spheres,
        ambient=0.35,
        smooth_shading=False,
        show_scalar_bar=False,
    )


def add_scene(
    plotter: pv.Plotter,
    cloud: DonorCloud,
    content: str,
    point_size: float,
) -> None:
    selected = highlighted_celltypes(content)
    xenium_background = ~np.isin(cloud.xenium_labels, selected)
    vhd_background = ~np.isin(cloud.vhd_labels, selected)
    add_point_layer(
        plotter, cloud.xenium_xyz[xenium_background],
        BACKGROUND_XENIUM_COLOR, XENIUM_BACKGROUND_OPACITY, point_size, False,
    )
    add_point_layer(
        plotter, cloud.vhd_xyz[vhd_background],
        BACKGROUND_VHD_COLOR, VHD_BACKGROUND_OPACITY, point_size, True,
    )
    for cell_type in selected:
        add_point_layer(
            plotter, cloud.xenium_xyz[cloud.xenium_labels == cell_type],
            HIGHLIGHT_PALETTE[cell_type], XENIUM_HIGHLIGHT_OPACITY,
            point_size, False,
        )
        add_point_layer(
            plotter, cloud.vhd_xyz[cloud.vhd_labels == cell_type],
            VHD_HIGHLIGHT_PALETTE[cell_type], VHD_HIGHLIGHT_OPACITY,
            point_size, True,
        )


def add_legend(plotter: pv.Plotter, content: str) -> None:
    selected = highlighted_celltypes(content)
    labels: list[list[str]] = []
    for cell_type in selected:
        short_name = cell_type.replace("D1_Island_", "D1 Island ")
        labels.extend(
            [
                [f"Xenium {short_name}", HIGHLIGHT_PALETTE[cell_type], "circle"],
                [
                    f"VisiumHD {short_name}",
                    VHD_HIGHLIGHT_PALETTE[cell_type],
                    "circle",
                ],
            ]
        )
    labels.extend(
        [
            ["Xenium other", BACKGROUND_XENIUM_COLOR, "circle"],
            ["VisiumHD other", BACKGROUND_VHD_COLOR, "circle"],
        ]
    )
    height = 0.085 if len(selected) == 1 else 0.125
    legend = plotter.add_legend(
        labels=labels,
        bcolor="white",
        border=False,
        size=(0.18, height),
        loc=None,
        background_opacity=0.72,
        font_family="arial",
        name="celltype_technology_legend",
    )
    legend.SetPosition(0.80, 0.96 - height)
    legend.SetPosition2(0.18, height)
    legend.GetEntryTextProperty().SetFontSize(6)
    legend.GetEntryTextProperty().SetBold(False)


def add_brain_reference_axes(plotter: pv.Plotter) -> None:
    plotter.add_axes(
        interactive=False,
        line_width=3,
        color="black",
        x_color="#D95F5F",
        y_color="#5FA35F",
        z_color="#5F7FD9",
        xlabel="ML",
        ylabel="DV",
        zlabel="AP",
        viewport=(0.0, 0.0, 0.22, 0.22),
        label_size=(0.34, 0.12),
    )


def rotation_x(angle: float) -> np.ndarray:
    c, s = np.cos(angle), np.sin(angle)
    return np.array([[1, 0, 0], [0, c, -s], [0, s, c]], dtype=float)


def rotation_y(angle: float) -> np.ndarray:
    c, s = np.cos(angle), np.sin(angle)
    return np.array([[c, 0, s], [0, 1, 0], [-s, 0, c]], dtype=float)


def set_camera(
    plotter: pv.Plotter,
    center: np.ndarray,
    initial_offset: np.ndarray,
    initial_up: np.ndarray,
    rotation: np.ndarray,
) -> None:
    plotter.camera.position = tuple(center + rotation @ initial_offset)
    plotter.camera.focal_point = tuple(center)
    plotter.camera.up = tuple(rotation @ initial_up)
    plotter.reset_camera_clipping_range()
    plotter.render()


def report_renderer(plotter: pv.Plotter) -> None:
    window = plotter.render_window
    window_class = window.GetClassName()
    capabilities = str(window.ReportCapabilities())
    print(f"VTK render window: {window_class}", flush=True)
    for line in capabilities.splitlines():
        if any(
            token in line.lower()
            for token in ("vendor string", "renderer string", "version string")
        ):
            print(line.strip(), flush=True)
    lowered = capabilities.lower()
    if window_class != "vtkEGLRenderWindow":
        raise RuntimeError(f"Expected vtkEGLRenderWindow; got {window_class}")
    if "llvmpipe" in lowered or "softpipe" in lowered:
        raise RuntimeError("VTK selected software rendering instead of the GPU")


def write_orbit(
    plotter: pv.Plotter,
    writer: cv2.VideoWriter,
    caption: str,
    center: np.ndarray,
    initial_offset: np.ndarray,
    initial_up: np.ndarray,
    rotation_function: Callable[[float], np.ndarray],
    frame_count: int,
    frame_offset: int,
    total_frames: int,
    started: float,
) -> None:
    plotter.add_text(
        caption,
        position=(0.025, 0.90),
        viewport=True,
        font_size=14,
        color="black",
        name="rotation_caption",
    )
    for local_index, angle in enumerate(
        np.linspace(0, 2 * np.pi, frame_count, endpoint=True)
    ):
        set_camera(
            plotter, center, initial_offset, initial_up,
            rotation_function(float(angle)),
        )
        rgb = np.asarray(plotter.image)
        expected = (int(plotter.window_size[1]), int(plotter.window_size[0]), 3)
        if rgb.shape != expected:
            raise ValueError(f"Unexpected frame shape {rgb.shape}; expected {expected}")
        writer.write(cv2.cvtColor(rgb, cv2.COLOR_RGB2BGR))
        completed = frame_offset + local_index + 1
        if completed == 1 or completed % 10 == 0 or completed == total_frames:
            elapsed = time.perf_counter() - started
            rate = completed / elapsed
            eta = (total_frames - completed) / rate / 60
            print(
                f"Frames {completed}/{total_frames} | "
                f"{rate:.2f} frame/s | ETA {eta:.1f} min",
                flush=True,
            )


def render_video(
    cloud: DonorCloud,
    content: str,
    path: Path,
    *,
    fps: int,
    seconds_per_rotation: float,
    window_size: tuple[int, int],
    point_size: float,
    overwrite: bool,
) -> None:
    prepare_output(path, overwrite)
    temporary = path.with_name(f"{path.stem}.tmp{path.suffix}")
    if temporary.exists():
        temporary.unlink()
    frame_count = max(2, int(round(fps * seconds_per_rotation)))
    writer = None
    plotter = pv.Plotter(off_screen=True, window_size=window_size)
    try:
        plotter.set_background("white")
        add_scene(plotter, cloud, content, point_size)
        add_legend(plotter, content)
        add_brain_reference_axes(plotter)
        plotter.view_xy()
        plotter.reset_camera()
        plotter.show(auto_close=False, interactive=False)
        report_renderer(plotter)
        center = np.asarray(plotter.camera.focal_point, dtype=float)
        initial_offset = np.asarray(plotter.camera.position, dtype=float) - center
        initial_up = np.asarray(plotter.camera.up, dtype=float)

        writer = cv2.VideoWriter(
            str(temporary), cv2.VideoWriter_fourcc(*"mp4v"),
            float(fps), tuple(window_size),
        )
        if not writer.isOpened():
            raise RuntimeError(f"Could not open MP4 writer: {temporary}")
        total_frames = 2 * frame_count
        started = time.perf_counter()
        write_orbit(
            plotter, writer, "Rotation about the ML axis", center,
            initial_offset, initial_up, rotation_x, frame_count, 0,
            total_frames, started,
        )
        write_orbit(
            plotter, writer, "Rotation about the DV axis", center,
            initial_offset, initial_up, rotation_y, frame_count, frame_count,
            total_frames, started,
        )
        writer.release()
        writer = None
        temporary.replace(path)
    finally:
        if writer is not None:
            writer.release()
        plotter.close()


def main() -> None:
    args = parse_args()
    root = git_root()
    for donor in args.donors:
        print(
            f"\nLoading final Xenium and VisiumHD coordinates for {donor}...",
            flush=True,
        )
        cloud = build_donor_cloud(root, donor)
        print(
            f"{donor}: Xenium={len(cloud.xenium_xyz):,}; "
            f"VisiumHD={len(cloud.vhd_xyz):,}",
            flush=True,
        )
        for content in args.contents:
            path = output_path(root, donor, content)
            print(f"\nRendering {path.name}", flush=True)
            render_video(
                cloud, content, path,
                fps=args.fps,
                seconds_per_rotation=args.seconds_per_rotation,
                window_size=tuple(args.window_size),
                point_size=args.point_size,
                overwrite=args.overwrite,
            )
            print(f"Saved: {path}", flush=True)


if __name__ == "__main__":
    main()


# Example usage
# -------------
# cd /dcs05/lieber/marmaypag/xenium_NAC_LIBD4125/xenium_NAC/code/11_Xenium_VisiumHD_alignment
# conda activate /dcs04/hicks/data/multi-sample-alignment-benchmark/envs/Spateo/
#
# All six full-quality videos (two donors x three D1 contents):
# python supp_video_Xenium_VisiumHD_3d_alignment.py --overwrite
#
# Br6660 only, all three videos, approximately smaller-file settings:
# python supp_video_Xenium_VisiumHD_3d_alignment.py \
#     --donors Br6660 \
#     --contents d1-a d1-b d1-a-b \
#     --fps 15 \
#     --seconds-per-rotation 8 \
#     --window-size 1440 1440 \
#     --point-size 3 \
#     --overwrite
